apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: khing-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: ghcr.io/chinathaip/k8s-cm-auto-reloader:4fb665f808337a7019bee2dcf642ca0ee1e88941
          resources:
            limits:
              cpu: "0.5" 
              memory: "512Mi"
            requests:
              cpu: "0.2"  
              memory: "256Mi"
          env:
          - name: NAME
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: NAME  
