apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: chinathai-operator-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8sops
    app.kubernetes.io/part-of: k8sops
    app.kubernetes.io/managed-by: kustomize
  name: chinathai-operator
  namespace: system
