name: Khing's CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup SHA
      run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build Docker Image
      run: docker build ./env-printer --file ./env-printer/Dockerfile  --tag ghcr.io/chinathaip/k8s-cm-auto-reloader:${{ env.GITHUB_SHA }}

    - name: Login ghcr.io
      uses: docker/login-action@v1.8.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: true

    - name: Push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: ./env-printer
        tags: |
          ghcr.io/chinathaip/k8s-cm-auto-reloader:${{ env.GITHUB_SHA }}
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
